Replace akka-http-core-experimental with akka-http-core
dtaniwaki/akka-pusher pull request #33
Opened 2016-08-26 06:57 UTC by tkqubo

This PR will update akka libraries, to use akka-pusher with akka-http.
⚠️ after this change, spray can no longer be supported, as it doesn't run with akka-http 2.4.x

2016-08-26 11:23 UTC, dtaniwaki commented
@tkqubo Thank you for the PR! Could you remove unnecessary version change such as Scalia version and squash the commits?
I will do it outside this PR if necessary.

2016-08-26 13:59 UTC, tkqubo commented
OK I removed unnecessary lines and tidied up commits :-)

And one thing I want to inform you that since Akka 2.4.0 dropped the support of Scala 2.10.x, I removed relevant lines.

2017-01-13 04:35 UTC, dtaniwaki requested changes
@tkqubo Please check the comments and update the branch.

2017-01-13 04:35 UTC, dtaniwaki commented on src/main/scala/com/github/dtaniwaki/akka_pusher/PusherActor.scala
> -  implicit val ec: ExecutionContext = system.dispatcher
Is this change necessary to update Akka version?

2017-01-13 04:35 UTC, dtaniwaki commented on src/test/resources/application.conf
> +  dispatcher {
ditto

2017-01-13 04:37 UTC, dtaniwaki requested changes

2017-01-13 04:37 UTC, dtaniwaki commented on .travis.yml
> +  - "sbt ++$TRAVIS_SCALA_VERSION clean coverage test"
Should be `clean test` if this change is for Scala 2.11.x?

2017-01-19 09:13 UTC, dtaniwaki commented
It seems your repository includes a lot of unnecessary changes. I will do the same change by myself. Thanks for the reporting!

2017-01-19 09:13 UTC, closed without merging

2017-01-20 03:53 UTC, tkqubo commented
Sorry for not responding long time.  I will leave this to you.  Thanks!